### ISSUE TITLE
Segmentation fault when run on some sources

### ISSUE THREAD

**Issue by X-Ryl669** [bkryza/clang-uml#18]
Built the version from master as of today. When run on [rlottie's repository](https://github.com/Samsung/rlottie) with this `.clang-uml` I get a segmentation fault and no puml file is generated. 

```yaml
compilation_database_dir: . 
output_directory: puml 
diagrams: 
  rlottie_class: 
    type: class 
    glob: 
      - ../rlottie/inc/*.h 
      - ../rlottie/src/lottie/*.h 
      - ../rlottie/src/vector/*.cpp 
      - ../rlottie/src/vector/*.h 
    using_namespace: 
      - rlottie 
    include: 
      namespaces: 
        - rlottie 
        - rlottie::internal
#    exclude:
#       namespaces:
#         - std
    plantuml:
      before:
        - 'title clang-uml class diagram model'

```

The cmake build line is: `mkdir build && cd build && cmake ../rlottie/ -DCMAKE_EXPORT_COMPILE_COMMANDS=ON`

**Comment by X-Ryl669** [comment]
Output from the tool:
```
...
[2022-03-04 16:35:15.143] [warning] [translation_unit_visitor.cc:399] Class MapType is templated but it's scope MapType is not - probably this is a specialization
[2022-03-04 16:35:15.144] [warning] [translation_unit_visitor.cc:399] Class MapType is templated but it's scope MapType is not - probably this is a specialization
[2022-03-04 16:35:15.144] [warning] [translation_unit_visitor.cc:399] Class MapType is templated but it's scope MapType is not - probably this is a specialization
[2022-03-04 16:35:15.144] [warning] [translation_unit_visitor.cc:399] Class MapType is templated but it's scope MapType is not - probably this is a specialization
[2022-03-04 16:35:15.144] [warning] [translation_unit_visitor.cc:399] Class MapType is templated but it's scope MapType is not - probably this is a specialization
[2022-03-04 16:35:15.144] [warning] [translation_unit_visitor.cc:399] Class MapType is templated but it's scope MapType is not - probably this is a specialization
[2022-03-04 16:35:15.144] [warning] [translation_unit_visitor.cc:399] Class MapType is templated but it's scope MapType is not - probably this is a specialization
[2022-03-04 16:35:15.144] [warning] [translation_unit_visitor.cc:399] Class MapType is templated but it's scope MapType is not - probably this is a specialization
[2022-03-04 16:35:15.145] [warning] [translation_unit_visitor.cc:399] Class MapType is templated but it's scope MapType is not - probably this is a specialization
[2022-03-04 16:35:15.145] [warning] [translation_unit_visitor.cc:399] Class MapType is templated but it's scope MapType is not - probably this is a specialization
[2022-03-04 16:35:15.145] [warning] [translation_unit_visitor.cc:399] Class MapType is templated but it's scope MapType is not - probably this is a specialization
[2022-03-04 16:35:15.145] [warning] [translation_unit_visitor.cc:399] Class MapType is templated but it's scope MapType is not - probably this is a specialization
[2022-03-04 16:35:15.145] [warning] [translation_unit_visitor.cc:399] Class MapType is templated but it's scope MapType is not - probably this is a specialization
[2022-03-04 16:35:15.146] [warning] [translation_unit_visitor.cc:399] Class MapType is templated but it's scope MapType is not - probably this is a specialization
[2022-03-04 16:35:15.146] [warning] [translation_unit_visitor.cc:399] Class MapType is templated but it's scope MapType is not - probably this is a specialization
[2022-03-04 16:35:15.146] [warning] [translation_unit_visitor.cc:399] Class MapType is templated but it's scope MapType is not - probably this is a specialization
[2022-03-04 16:35:15.146] [warning] [translation_unit_visitor.cc:399] Class MapType is templated but it's scope MapType is not - probably this is a specialization
[2022-03-04 16:35:15.147] [warning] [translation_unit_visitor.cc:399] Class MapType is templated but it's scope MapType is not - probably this is a specialization
[2022-03-04 16:35:15.147] [warning] [translation_unit_visitor.cc:399] Class MapType is templated but it's scope MapType is not - probably this is a specialization
[2022-03-04 16:35:15.147] [warning] [translation_unit_visitor.cc:399] Class MapType is templated but it's scope MapType is not - probably this is a specialization
[2022-03-04 16:35:15.147] [warning] [translation_unit_visitor.cc:399] Class MapType is templated but it's scope MapType is not - probably this is a specialization
[2022-03-04 16:35:15.147] [warning] [translation_unit_visitor.cc:399] Class MapType is templated but it's scope MapType is not - probably this is a specialization
[2022-03-04 16:35:15.147] [warning] [translation_unit_visitor.cc:399] Class MapType is templated but it's scope MapType is not - probably this is a specialization
[2022-03-04 16:35:15.147] [warning] [translation_unit_visitor.cc:399] Class MapType is templated but it's scope MapType is not - probably this is a specialization
[2022-03-04 16:35:15.148] [warning] [translation_unit_visitor.cc:399] Class MapType is templated but it's scope MapType is not - probably this is a specialization
[2022-03-04 16:35:15.148] [warning] [translation_unit_visitor.cc:399] Class MapType is templated but it's scope MapType is not - probably this is a specialization
[2022-03-04 16:35:15.148] [warning] [translation_unit_visitor.cc:399] Class MapType is templated but it's scope MapType is not - probably this is a specialization
[2022-03-04 16:35:15.148] [warning] [translation_unit_visitor.cc:399] Class MapType is templated but it's scope MapType is not - probably this is a specialization
[2022-03-04 16:35:15.149] [warning] [element.cc:42] Skipping relationship '' - aggregation - 'LOTMask' due empty destination
[2022-03-04 16:35:15.149] [warning] [element.cc:42] Skipping relationship '' - aggregation - 'LOTMask' due empty destination
[2022-03-04 16:35:15.150] [warning] [element.cc:42] Skipping relationship '' - aggregation - 'LOTMask' due empty destination
[2022-03-04 16:35:15.150] [warning] [element.cc:42] Skipping relationship '' - aggregation - 'LOTMask' due empty destination
Erreur de segmentation (core dumped)
```
When run under gdb:
```
Thread 1 "clang-uml" received signal SIGSEGV, Segmentation fault.
fmt::v8::basic_format_parse_context<char, fmt::v8::detail::error_handler>::begin (this=0x7fffff7ff160) at /usr/include/fmt/core.h:652
652	   return format_str_.begin();
(gdb) bt
#0  fmt::v8::basic_format_parse_context<char, fmt::v8::detail::error_handler>::begin (this=0x7fffff7ff160) at /usr/include/fmt/core.h:652
#1  0x0000555555661237 in fmt::v8::formatter<fmt::v8::basic_string_view<char>, char, void>::parse<fmt::v8::basic_format_parse_context<char, fmt::v8::detail::error_handler> > (this=0x7fffff7ff0b0, ctx=...) at /usr/include/fmt/core.h:2977
#2  0x000055555565d347 in fmt::v8::formatter<fmt::v8::join_view<__gnu_cxx::__normal_iterator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >, __gnu_cxx::__normal_iterator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >, char>, char, void>::parse<fmt::v8::basic_format_parse_context<char, fmt::v8::detail::error_handler> > (this=0x7fffff7ff0b0, ctx=...) at /usr/include/fmt/format.h:2817
#3  0x00005555556584b5 in fmt::v8::detail::value<fmt::v8::basic_format_context<fmt::v8::appender, char> >::format_custom_arg<fmt::v8::join_view<__gnu_cxx::__normal_iterator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >, __gnu_cxx::__normal_iterator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >, char>, fmt::v8::formatter<fmt::v8::join_view<__gnu_cxx::__normal_iterator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >, __gnu_cxx::__normal_iterator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >, char>, char, void> > (arg=0x7fffff7ff550, parse_ctx=..., ctx=...) at /usr/include/fmt/core.h:1279
#4  0x00005555555ed3bd in fmt::v8::basic_format_arg<fmt::v8::basic_format_context<fmt::v8::appender, char> >::handle::format (this=0x0, parse_ctx=..., ctx=...) at /usr/include/fmt/core.h:1558
#5  0x00005555555e8597 in fmt::v8::detail::default_arg_formatter<char>::operator() (this=0x7fffff7ff220, h=...) at /usr/include/fmt/format.h:2202
#6  0x00005555555e470b in fmt::v8::visit_format_arg<fmt::v8::detail::default_arg_formatter<char>, fmt::v8::basic_format_context<fmt::v8::appender, char> > (arg=..., vis=...) at /usr/include/fmt/core.h:1622
#7  fmt::v8::detail::vformat_to<char> (buf=..., fmt=..., args=..., loc=...) at /usr/include/fmt/format.h:2931
#8  0x00007ffff616ea98 in fmt::v8::vformat[abi:cxx11](fmt::v8::basic_string_view<char>, fmt::v8::basic_format_args<fmt::v8::basic_format_context<fmt::v8::appender, char> >) () from /usr/lib/libfmt.so.8
#9  0x00005555556e0417 in fmt::v8::format<fmt::v8::join_view<__gnu_cxx::__normal_iterator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >, __gnu_cxx::__normal_iterator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >, char> > (fmt=...) at /usr/include/fmt/core.h:3119
#10 clanguml::cx::util::ns[abi:cxx11](cppast::cpp_entity const&) (e=...) at /home/cyril/Dev/clang-uml/src/cx/util.cc:93
#11 0x00005555556e0a98 in clanguml::cx::util::ns[abi:cxx11](cppast::cpp_type const&, cppast::cpp_entity_index const&) (t=..., idx=...) at /home/cyril/Dev/clang-uml/src/cx/util.cc:151
#12 0x00005555556e0015 in clanguml::cx::util::full_name[abi:cxx11](cppast::cpp_type const&, cppast::cpp_entity_index const&, bool) (t=..., idx=..., inside_class=false) at /home/cyril/Dev/clang-uml/src/cx/util.cc:67
#13 0x0000555555683e89 in clanguml::class_diagram::visitor::translation_unit_context::get_type_alias_final (this=0x7fffffffcc30, t=...) at /home/cyril/Dev/clang-uml/src/class_diagram/visitor/translation_unit_context.cc:115
#14 0x0000555555683ed1 in clanguml::class_diagram::visitor::translation_unit_context::get_type_alias_final (this=0x7fffffffcc30, t=...) at /home/cyril/Dev/clang-uml/src/class_diagram/visitor/translation_unit_context.cc:118
#15 0x0000555555683ed1 in clanguml::class_diagram::visitor::translation_unit_context::get_type_alias_final (this=0x7fffffffcc30, t=...) at /home/cyril/Dev/clang-uml/src/class_diagram/visitor/translation_unit_context.cc:118
#16 0x0000555555683ed1 in clanguml::class_diagram::visitor::translation_unit_context::get_type_alias_final (this=0x7fffffffcc30, t=...) at /home/cyril/Dev/clang-uml/src/class_diagram/visitor/translation_unit_context.cc:118
#17 0x0000555555683ed1 in clanguml::class_diagram::visitor::translation_unit_context::get_type_alias_final (this=0x7fffffffcc30, t=...) at /home/cyril/Dev/clang-uml/src/class_diagram/visitor/translation_unit_context.cc:118
#18 0x0000555555683ed1 in clanguml::class_diagram::visitor::translation_unit_context::get_type_alias_final (this=0x7fffffffcc30, t=...) at /home/cyril/Dev/clang-uml/src/class_diagram/visitor/translation_unit_context.cc:118
#19 0x0000555555683ed1 in clanguml::class_diagram::visitor::translation_unit_context::get_type_alias_final (this=0x7fffffffcc30, t=...) at /home/cyril/Dev/clang-uml/src/class_diagram/visitor/translation_unit_context.cc:118
#20 0x0000555555683ed1 in clanguml::class_diagram::visitor::translation_unit_context::get_type_alias_final (this=0x7fffffffcc30, t=...) at /home/cyril/Dev/clang-uml/src/class_diagram/visitor/translation_unit_context.cc:118
#21 0x0000555555683ed1 in clanguml::class_diagram::visitor::translation_unit_context::get_type_alias_final (this=0x7fffffffcc30, t=...) at /home/cyril/Dev/clang-uml/src/class_diagram/visitor/translation_unit_context.cc:118
#22 0x0000555555683ed1 in clanguml::class_diagram::visitor::translation_unit_context::get_type_alias_final (this=0x7fffffffcc30, t=...) at /home/cyril/Dev/clang-uml/src/class_diagram/visitor/translation_unit_context.cc:118
#23 0x0000555555683ed1 in clanguml::class_diagram::visitor::translation_unit_context::get_type_alias_final (this=0x7fffffffcc30, t=...) at /home/cyril/Dev/clang-uml/src/class_diagram/visitor/translation_unit_context.cc:118
#24 0x0000555555683ed1 in clanguml::class_diagram::visitor::translation_unit_context::get_type_alias_final (this=0x7fffffffcc30, t=...) at /home/cyril/Dev/clang-uml/src/class_diagram/visitor/translation_unit_context.cc:118
#25 0x0000555555683ed1 in clanguml::class_diagram::visitor::translation_unit_context::get_type_alias_final (this=0x7fffffffcc30, t=...) at /home/cyril/Dev/clang-uml/src/class_diagram/visitor/translation_unit_context.cc:118
#26 0x0000555555683ed1 in clanguml::class_diagram::visitor::translation_unit_context::get_type_alias_final (this=0x7fffffffcc30, t=...) at /home/cyril/Dev/clang-uml/src/class_diagram/visitor/translation_unit_context.cc:118
#27 0x0000555555683ed1 in clanguml::class_diagram::visitor::translation_unit_context::get_type_alias_final (this=0x7fffffffcc30, t=...) at /home/cyril/Dev/clang-uml/src/class_diagram/visitor/translation_unit_context.cc:118
#28 0x0000555555683ed1 in clanguml::class_diagram::visitor::translation_unit_context::get_type_alias_final (this=0x7fffffffcc30, t=...) at /home/cyril/Dev/clang-uml/src/class_diagram/visitor/translation_unit_context.cc:118
#29 0x0000555555683ed1 in clanguml::class_diagram::visitor::translation_unit_context::get_type_alias_final (this=0x7fffffffcc30, t=...) at /home/cyril/Dev/clang-uml/src/class_diagram/visitor/translation_unit_context.cc:118
#30 0x0000555555683ed1 in clanguml::class_diagram::visitor::translation_unit_context::get_type_alias_final (this=0x7fffffffcc30, t=...) at /home/cyril/Dev/clang-uml/src/class_diagram/visitor/translation_unit_context.cc:118
#31 0x0000555555683ed1 in clanguml::class_diagram::visitor::translation_unit_context::get_type_alias_final (this=0x7fffffffcc30, t=...) at /home/cyril/Dev/clang-uml/src/class_diagram/visitor/translation_unit_context.cc:118
#32 0x0000555555683ed1 in clanguml::class_diagram::visitor::translation_unit_context::get_type_alias_final (this=0x7fffffffcc30, t=...) at /home/cyril/Dev/clang-uml/src/class_diagram/visitor/translation_unit_context.cc:118
#33 0x0000555555683ed1 in clanguml::class_diagram::visitor::translation_unit_context::get_type_alias_final (this=0x7fffffffcc30, t=...) at /home/cyril/Dev/clang-uml/src/class_diagram/visitor/translation_unit_context.cc:118
#34 0x0000555555683ed1 in clanguml::class_diagram::visitor::translation_unit_context::get_type_alias_final (this=0x7fffffffcc30, t=...) at /home/cyril/Dev/clang-uml/src/class_diagram/visitor/translation_unit_context.cc:118
#35 0x0000555555683ed1 in clanguml::class_diagram::visitor::translation_unit_context::get_type_alias_final (this=0x7fffffffcc30, t=...) at /home/cyril/Dev/clang-uml/src/class_diagram/visitor/translation_unit_context.cc:118
#36 0x0000555555683ed1 in clanguml::class_diagram::visitor::translation_unit_context::get_type_alias_final (this=0x7fffffffcc30, t=...) at /home/cyril/Dev/clang-uml/src/class_diagram/visitor/translation_unit_context.cc:118
#37 0x0000555555683ed1 in clanguml::class_diagram::visitor::translation_unit_context::get_type_alias_final (this=0x7fffffffcc30, t=...) at /home/cyril/Dev/clang-uml/src/class_diagram/visitor/translation_unit_context.cc:118
#38 0x0000555555683ed1 in clanguml::class_diagram::visitor::translation_unit_context::get_type_alias_final (this=0x7fffffffcc30, t=...) at /home/cyril/Dev/clang-uml/src/class_diagram/visitor/translation_unit_context.cc:118
[list goes on with more than 22000 frame context, I gave up trying to walk it up]
```

**Comment by bkryza** [comment]
@X-Ryl669 Thanks for the issue and stack trace - unfortunately the tool is not yet very resilient with respect to edge-cases - in this case this an issue with namespace resolution of some cpp entity: https://github.com/bkryza/clang-uml/blob/master/src/cx/util.cc#L151

I'm actually refactoring currently namespace handling on a separate branch, so hopefully I'll manage to fix this somewhere next week. I'll check this repo and your .clang-uml config to try to make sure it helps.

If you'd like you can try to further limit the glob pattern in the .clang-uml to start with a minimal set of h and cpp files necessary for a specific diagram, and if that works extend it incrementally...

**Comment by X-Ryl669** [comment]
This is what I did. But the project use a single header strategy (rlottiecommon.h) so it doesn't go very far. Looking forward for your fixes, thanks!

**Comment by bkryza** [comment]
@X-Ryl669 

Please try again with the latest master (also update submodules!). The segmentation fault was actually a trivial bug, however the code base had more challenging features that were not supported before, including anonymous inner structs and nested template specialization parameters which were reported as unexposed (i.e. simple strings) by libclang - I've also fixed those to some extent...

I've tested with the following .clang-uml file (please make sure you have the `puml` output directory before running clang-uml):
```yaml
compilation_database_dir: .
output_directory: puml
diagrams:
  rlottie_class:
    type: class
    glob:
      - ../rlottie/inc/rlottie.h
      - ../rlottie/inc/rlottiecommon.h
      - ../rlottie/src/lottie/*.h
      - ../rlottie/src/lottie/*.cpp
      - ../rlottie/src/vector/*.h
      - ../rlottie/src/vector/*.cpp
    layout:
      Animation:
        - up: Surface
    using_namespace:
      - rlottie
    include:
      namespaces:
        - rlottie
        - AnimationImpl
    plantuml:
      before:
        - 'title rlottie class diagram'
```

Since the generated diagram is very big also make sure to increase the maximum image size for plantuml, e.g.

```
plantuml -tpng -DPLANTUML_LIMIT_SIZE=20000 puml/rlottie_class.puml
```

Like I said, this generates a very big diagram, so not sure if this will be very useful, you might want to experiment with the include filters to split it into several diagrams...

One more caveat is that rlottie has several classes which are not in the rlottie namespace, i.e. they will be skipped, unless you include them directly (in the example above it's done for AnimationImpl class)...

Please let me know if this helped.

**Comment by X-Ryl669** [comment]
It works a lot better. I guess you are building on a Mac. On linux, the current master doesn't build, I add to apply this patch:
```diff
diff --git a/src/class_diagram/visitor/translation_unit_visitor.cc b/src/class_diagram/visitor/translation_unit_visitor.cc
index 4fc7ce5..52a1d0e 100644
--- a/src/class_diagram/visitor/translation_unit_visitor.cc
+++ b/src/class_diagram/visitor/translation_unit_visitor.cc
@@ -730,7 +730,7 @@ void translation_unit_visitor::process_field(
 
 #ifndef __APPLE__
     LOG_DBG("Processing field {} with unreferenced type of kind {}", mv.name(),
-        tr.kind());
+        (int)tr.kind());
 #endif
 
     if (tr.kind() == cppast::cpp_type_kind::builtin_t) {
@@ -1216,7 +1216,7 @@ bool translation_unit_visitor::find_relationships(const cppast::cpp_type &t_,
 
 #ifndef __APPLE__
     LOG_DBG("Finding relationships for type {}, {}, {}", cppast::to_string(t_),
-        t_.kind(), fn);
+        (int)t_.kind(), fn);
 #endif
 
     relationship_t relationship_type = relationship_hint;
diff --git a/src/package_diagram/visitor/translation_unit_visitor.cc b/src/package_diagram/visitor/translation_unit_visitor.cc
index 043729c..6419328 100644
--- a/src/package_diagram/visitor/translation_unit_visitor.cc
+++ b/src/package_diagram/visitor/translation_unit_visitor.cc
@@ -381,7 +381,7 @@ bool translation_unit_visitor::find_relationships(const cppast::cpp_type &t_,
 
 #ifndef __APPLE__
     LOG_DBG("Finding relationships for type {}, {}, {}", cppast::to_string(t_),
-        t_.kind(), fn);
+        (int)t_.kind(), fn);
 #endif
 
     relationship_t relationship_type = relationship_hint;
```

If I try to use wildcard (include everything), I get an exception that matches your comment:

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  Name cannot contain namespace: model::Filter
Abandon (core dumped)
```

But it works with partial including files. Thanks!

**Comment by bkryza** [comment]
@X-Ryl669 thanks for checking. The compilation error is strange as I only build on Linux (Ubuntu 21.10) with GCC:
```
❯ g++ --version
g++ (Ubuntu 11.2.0-7ubuntu2) 11.2.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

Also the CI tests and build on GitHub Actions are run on Linux (https://github.com/bkryza/clang-uml/blob/master/.github/workflows/build.yml). Can you please paste some details on your environment (Linux version, GCC/Clang version, libclang version, fmt version, spdlog version?) - I will try to investigate...

As to the inclusion/exclusion filters this is on my to-refactor list (for now it's just basic comparison of string representation of entities), but not sure when this will be finished...

**Comment by X-Ryl669** [comment]
The exact error is:
```
In file included from /usr/include/spdlog/fmt/fmt.h:25,
                 from /usr/include/spdlog/common.h:36,
                 from /usr/include/spdlog/spdlog.h:12,
                 from /home/cyril/Dev/clang-uml/src/util/util.h:20,
                 from /home/cyril/Dev/clang-uml/src/common/model/element.h:23,
                 from /home/cyril/Dev/clang-uml/src/class_diagram/model/class.h:24,
                 from /home/cyril/Dev/clang-uml/src/class_diagram/model/diagram.h:20,
                 from /home/cyril/Dev/clang-uml/src/config/config.h:20,
                 from /home/cyril/Dev/clang-uml/src/package_diagram/visitor/translation_unit_visitor.h:20,
                 from /home/cyril/Dev/clang-uml/src/package_diagram/visitor/translation_unit_visitor.cc:19:
/usr/include/fmt/core.h: In instantiation of 'constexpr fmt::v8::detail::value<Context> fmt::v8::detail::make_arg(T&&) [with bool IS_PACKED = true; Context = fmt::v8::basic_format_context<fmt::v8::appender, char>; fmt::v8::detail::type <anonymous> = fmt::v8::detail::type::custom_type; T = cppast::cpp_type_kind&; typename std::enable_if<IS_PACKED, int>::type <anonymous> = 0]':
/usr/include/fmt/core.h:1855:77:   required from 'constexpr fmt::v8::format_arg_store<Context, Args>::format_arg_store(T&& ...) [with T = {const char*&, int&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, cppast::cpp_type_kind&, const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&}; Context = fmt::v8::basic_format_context<fmt::v8::appender, char>; Args = {const char*, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, cppast::cpp_type_kind, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >}]'
/usr/include/fmt/core.h:1872:38:   required from 'constexpr fmt::v8::format_arg_store<Context, typename std::remove_cv<typename std::remove_reference<Args>::type>::type ...> fmt::v8::make_format_args(Args&& ...) [with Context = fmt::v8::basic_format_context<fmt::v8::appender, char>; Args = {const char*&, int&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, cppast::cpp_type_kind&, const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&}]'
/usr/include/spdlog/logger.h:332:68:   required from 'void spdlog::logger::log_(spdlog::source_loc, spdlog::level::level_enum, spdlog::string_view_t, Args&& ...) [with Args = {const char*, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, cppast::cpp_type_kind, const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&}; spdlog::string_view_t = fmt::v8::basic_string_view<char>]'
/usr/include/spdlog/logger.h:83:13:   required from 'void spdlog::logger::log(spdlog::source_loc, spdlog::level::level_enum, fmt::v8::format_string<T ...>, Args&& ...) [with Args = {const char*, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, cppast::cpp_type_kind, const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&}; fmt::v8::format_string<T ...> = fmt::v8::basic_format_string<char, const char*, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, cppast::cpp_type_kind, const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&>]'
/usr/include/spdlog/logger.h:89:12:   required from 'void spdlog::logger::log(spdlog::level::level_enum, fmt::v8::format_string<T ...>, Args&& ...) [with Args = {const char*, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, cppast::cpp_type_kind, const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&}; fmt::v8::format_string<T ...> = fmt::v8::basic_format_string<char, const char*, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, cppast::cpp_type_kind, const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&>]'
/usr/include/spdlog/logger.h:152:12:   required from 'void spdlog::logger::debug(fmt::v8::format_string<T ...>, Args&& ...) [with Args = {const char*, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, cppast::cpp_type_kind, const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&}; fmt::v8::format_string<T ...> = fmt::v8::basic_format_string<char, const char*, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, cppast::cpp_type_kind, const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&>]'
/usr/include/spdlog/spdlog.h:151:32:   required from 'void spdlog::debug(fmt::v8::format_string<T ...>, Args&& ...) [with Args = {const char*, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, cppast::cpp_type_kind, const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&}; fmt::v8::format_string<T ...> = fmt::v8::basic_format_string<char, const char*, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, cppast::cpp_type_kind, const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&>]'
/home/cyril/Dev/clang-uml/src/package_diagram/visitor/translation_unit_visitor.cc:383:5:   required from here
/usr/include/fmt/core.h:1728:7: error: static assertion failed: Cannot format an argument. To make type T formattable provide a formatter<T> specialization: https://fmt.dev/latest/api.html#udt
 1728 |       formattable,
      |       ^~~~~~~~~~~
/usr/include/fmt/core.h:1728:7: note: 'formattable' evaluates to false
```
I'm using a Arch linux system, so likely last-like version of everything. G++ 11.2, FMT_VERSION 80101.

**Comment by bkryza** [comment]
@X-Ryl669 Thanks, the issue was with the latest spdlog/fmt version not allowing implicit cast from `enum class` - the current master should now build directly...
